CREATE TABLE CUSTOMER_W_TER
(
  CUSTOMERNUMBER INTEGER
, CUSTOMERNAME VARCHAR(50)
, CONTACTLASTNAME VARCHAR(50)
, CONTACTFIRSTNAME VARCHAR(50)
, PHONE VARCHAR(50)
, ADDRESSLINE1 VARCHAR(50)
, ADDRESSLINE2 VARCHAR(50)
, CITY VARCHAR(50)
, STATE VARCHAR(50)
, POSTALCODE VARCHAR(15)
, COUNTRY VARCHAR(50)
, EMPLOYEENUMBER INTEGER
, CREDITLIMIT NUMERIC(18, 4)
, TERRITORY VARCHAR(10)
, TERRITORY_COLOR VARCHAR(7)
)
;