CREATE TABLE PRODUCTS
(
  PRODUCTCODE VARCHAR(50)
, PRODUCTNAME VARCHAR(70)
, PRODUCTLINE VARCHAR(50)
, PRODUCTSCALE VARCHAR(10)
, PRODUCTVENDOR VARCHAR(50)
, PRODUCTDESCRIPTION LONG VARCHAR
, QUANTITYINSTOCK SMALLINT
, BUYPRICE BIGINT
, MSRP BIGINT
)
;