-- SQLINES DEMO *** rated by MySQL Workbench
-- SQLINES DEMO *** 4:48:15 WEST
-- SQLINES DEMO ***    Version: 1.0
-- SQLINES DEMO *** orward Engineering

/* SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0; */
/* SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0; */
/* SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'; */

-- SQLINES DEMO *** ------------------------------------
-- Schema nz
-- SQLINES DEMO *** ------------------------------------

-- SQLINES DEMO *** ------------------------------------
-- Schema nz
-- SQLINES DEMO *** ------------------------------------
CREATE SCHEMA IF NOT EXISTS nz ;
USE `nz` ;

-- SQLINES DEMO *** ------------------------------------
-- SQLINES DEMO *** _TER`
-- SQLINES DEMO *** ------------------------------------
CREATE TABLE IF NOT EXISTS CUSTOMER_W_TER (
  `CUSTOMERNUMBER` INT NOT NULL,
  `CUSTOMERNAME` VARCHAR(50) NULL DEFAULT NULL,
  `PHONE` VARCHAR(50) NULL DEFAULT NULL,
  `ADDRESS` VARCHAR(50) NULL DEFAULT NULL,
  `CITY` VARCHAR(50) NULL DEFAULT NULL,
  `STATE` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`CUSTOMERNUMBER`));


-- SQLINES DEMO *** ------------------------------------
-- Table `ORDERS`
-- SQLINES DEMO *** ------------------------------------
CREATE TABLE IF NOT EXISTS ORDERS (
  `ORDERNUMBER` INT NOT NULL,
  `ORDERDATE` TIMESTAMP(0) NOT NULL,
  `REQUIREDDATE` TIMESTAMP(0) NOT NULL,
  `SHIPPEDDATE` TIMESTAMP(0) NOT NULL,
  `CUSTOMERNUMBER` INT NOT NULL,
  PRIMARY KEY (`ORDERNUMBER`));


-- SQLINES DEMO *** ------------------------------------
-- Table `PRODUCTS`
-- SQLINES DEMO *** ------------------------------------
CREATE TABLE IF NOT EXISTS PRODUCTS (
  `PRODUCTCODE` VARCHAR(50) NOT NULL,
  `PRODUCTNAME` VARCHAR(70) NULL DEFAULT NULL,
  `PRODUCTVENDOR` VARCHAR(50) NULL DEFAULT NULL,
  `STOCK` SMALLINT NULL DEFAULT NULL,
  `PRICEINNZDOLLAR` BIGINT NULL DEFAULT NULL,
  `MSRP` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`PRODUCTCODE`));


-- SQLINES DEMO *** ------------------------------------
-- Table `DIM_TIME`
-- SQLINES DEMO *** ------------------------------------
CREATE TABLE IF NOT EXISTS DIM_TIME (
  `TIME_ID` VARCHAR(10) NOT NULL,
  `MONTH_ID` INT NULL DEFAULT NULL,
  `QTR_ID` INT NULL DEFAULT NULL,
  `YEAR_ID` INT NULL DEFAULT NULL,
  PRIMARY KEY (`TIME_ID`));


-- SQLINES DEMO *** ------------------------------------
-- Table `ORDERFACT`
-- SQLINES DEMO *** ------------------------------------
CREATE TABLE IF NOT EXISTS ORDERFACT (
  `ORDERNUMBER` INT NOT NULL,
  `PRODUCTCODE` VARCHAR(50) NOT NULL,
  `CUSTOMERNUMBER` INT NOT NULL,
  `TIME_ID` VARCHAR(10) NOT NULL,
  `QUANTITYORDERED` INT NULL DEFAULT NULL,
  `PRICEEACH` DECIMAL(18,4) NULL DEFAULT NULL,
  `TOTALPRICE` DECIMAL(64,0) NULL DEFAULT NULL,
  CONSTRAINT `fk_ORDERFACT_1`
    FOREIGN KEY (`CUSTOMERNUMBER`)
    REFERENCES CUSTOMER_W_TER (`CUSTOMERNUMBER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ORDERFACT_2`
    FOREIGN KEY (`ORDERNUMBER`)
    REFERENCES ORDERS (`ORDERNUMBER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ORDERFACT_3`
    FOREIGN KEY (`PRODUCTCODE`)
    REFERENCES PRODUCTS (`PRODUCTCODE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ORDERFACT_4`
    FOREIGN KEY (`TIME_ID`)
    REFERENCES DIM_TIME (`TIME_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX fk_ORDERFACT_1_idx ON ORDERFACT (`CUSTOMERNUMBER` ASC) VISIBLE;

CREATE INDEX fk_ORDERFACT_2_idx ON ORDERFACT (`ORDERNUMBER` ASC) VISIBLE;

CREATE INDEX fk_ORDERFACT_3_idx ON ORDERFACT (`PRODUCTCODE` ASC) VISIBLE;

CREATE INDEX fk_ORDERFACT_4_idx ON ORDERFACT (`TIME_ID` ASC) VISIBLE;


/* SET SQL_MODE=@OLD_SQL_MODE; */
/* SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS; */
/* SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS; */
