CREATE TABLE ORDERFACT
(
  ORDERNUMBER INTEGER
, PRODUCTCODE VARCHAR(50)
, QUANTITYORDERED INTEGER
, PRICEEACH NUMERIC(18, 4)
, ORDERLINENUMBER INTEGER
, TOTALPRICE NUMERIC(64, 0)
, ORDERDATE TIMESTAMP
, REQUIREDDATE TIMESTAMP
, SHIPPEDDATE TIMESTAMP
, STATUS VARCHAR(15)
, COMMENTS LONG VARCHAR
, CUSTOMERNUMBER INTEGER
, TIME_ID VARCHAR(10)
, QTR_ID BIGINT
, MONTH_ID BIGINT
, YEAR_ID BIGINT
)
;
